# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09f74b8ddf1a5d45e6163d014e6c0033651980fe8b35dbf957836b1e7a2a6c7167f43fd491d234741d406c2ffa4813ada00c20a65aea5e583b4d673f5837bc9

test:
  secret_key_base: 20e73bc6dffa516e3db0921dd1eab204692eed33d7105973cbfad71d3e119d1f18762c6b7d48b4304b67449c300df92a66ae7a97086accd76c5302534a7c791c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
